### ISSUE TITLE
Latest update crashing the game after finishing a quest

### ISSUE THREAD

**Issue by Dwyriel** [Strackeror/HealthNotes#2]
First things first: I'm on linux and this might be a linux specific issue.

Latest update for version 15.22 is leading to crashes after completing a quest and returning to base (past the post quest screen, after it saves the game, unloads the current map and starts loading the base).

Using the updated Loader but the previous version of HealthNotes, but modifying the string in the binary file from "421652" to "421740" works fine without crashes.

Here's the crash dump from wine: [dump.txt](https://github.com/user-attachments/files/15686425/dump.txt)

**Comment by Strackeror** [comment]
Huh, weird, i'll check that out, I didn't try finishing a quest with it so it might also happen on windows

**Comment by Dwyriel** [comment]
Seems like it does affect Windows as well

![image](https://github.com/Strackeror/HealthNotes/assets/61030926/6e54fa26-7f7f-44d2-81d2-fc2223e6948b)

**Comment by Dwyriel** [comment]
fixed by 51bbd8118f9bd30a7eaec5b5db4f4ad0ac020317
